/** Compile reviewed execution authority into the Worker; no runtime URL trust. */
import { constants } from "node:fs";
import { mkdir, open, readdir, realpath, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { findProject } from "../src/lib/projects.mjs";
import {
  assertSquadsExecutionIndex,
  executionSha256,
  MAX_EXECUTION_JSON_BYTES,
  parseSquadsBindingLedger,
  validateSquadsExecutionContext,
} from "../src/lib/squads-execution";
import {
  parseExecutionRegistry,
  type SquadsExecutionRegistry,
} from "../src/lib/squads-execution-registry";

async function boundedFile(
  root: string,
  relative: string,
): Promise<Uint8Array> {
  const path = join(root, relative);
  const actual = await realpath(path);
  if (actual !== path || !actual.startsWith(`${root}${sep}`))
    throw new TypeError("Execution source must not traverse symlinks");
  const handle = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW);
  try {
    const stat = await handle.stat();
    if (!stat.isFile() || stat.size < 1 || stat.size > MAX_EXECUTION_JSON_BYTES)
      throw new RangeError("Execution source must be a bounded regular file");
    const bytes = new Uint8Array(MAX_EXECUTION_JSON_BYTES + 1);
    let length = 0;
    while (length < bytes.length) {
      const read = await handle.read(
        bytes,
        length,
        bytes.length - length,
        null,
      );
      if (!read.bytesRead) break;
      length += read.bytesRead;
    }
    if (length > MAX_EXECUTION_JSON_BYTES)
      throw new RangeError("Execution source grew beyond bounds");
    return bytes.slice(0, length);
  } finally {
    await handle.close();
  }
}

export async function compileSquadsExecutionRegistry(
  directory: string,
): Promise<SquadsExecutionRegistry> {
  const root = await realpath(directory);
  const entries = await readdir(join(root, "funding/executions"), {
    withFileTypes: true,
  });
  if (
    entries.length !== 1 ||
    entries[0].name !== "ledger.json" ||
    !entries[0].isFile()
  )
    throw new TypeError(
      "Execution authority directory must contain only the canonical ledger.json",
    );
  const ledger = parseSquadsBindingLedger(
    await boundedFile(root, "funding/executions/ledger.json"),
  );
  const contexts: SquadsExecutionRegistry["contexts"] = [];
  let totalBytes = 0;
  for (const binding of ledger) {
    const project = findProject(binding.projectId);
    if (
      !project ||
      project.id !== binding.projectId ||
      project.reward.kind !== "monthly-pool"
    )
      throw new TypeError("Execution project is not canonical");
    const cycle = `cycles/${binding.projectId}/${binding.cycleId}`;
    const [allocationBytes, planBytes] = await Promise.all([
      boundedFile(root, `${cycle}/allocation.json`),
      boundedFile(root, `${cycle}/execution-plan.json`),
    ]);
    totalBytes += allocationBytes.byteLength + planBytes.byteLength;
    if (totalBytes > MAX_EXECUTION_JSON_BYTES * 0.75)
      throw new RangeError("Compiled execution inputs exceed registry budget");
    await validateSquadsExecutionContext({
      projectId: binding.projectId,
      allocationBytes,
      planBytes,
      baseLedger: ledger,
      ledger,
    });
    contexts.push({
      projectId: binding.projectId,
      cycleId: binding.cycleId,
      allocationBase64: Buffer.from(allocationBytes).toString("base64"),
      planBase64: Buffer.from(planBytes).toString("base64"),
      allocationSha256: await executionSha256(allocationBytes),
      planSha256: binding.planSha256,
    });
  }
  return parseExecutionRegistry(
    JSON.stringify({ schemaVersion: 1, ledger, contexts }),
  );
}

export async function syncSquadsExecutionRegistry(
  directory: string,
): Promise<void> {
  const registry = await compileSquadsExecutionRegistry(directory);
  const modulePath = join(
    directory,
    "src/lib/squads-execution-registry.generated.ts",
  );
  await mkdir(dirname(modulePath), { recursive: true });
  await writeFile(
    modulePath,
    `/** Generated by scripts/sync-squads-execution-registry.ts. Do not edit. */\nexport const SQUADS_EXECUTION_REGISTRY_JSON =\n  '${JSON.stringify(registry)}';\n`,
  );
  const index = assertSquadsExecutionIndex({
    schemaVersion: 1,
    executions: registry.contexts.map(
      ({ projectId, cycleId, allocationSha256, planSha256 }) => ({
        projectId,
        cycleId,
        allocationSha256,
        planSha256,
        binding: registry.ledger.find((row) => row.planSha256 === planSha256),
        observationUrl: `https://api.slop.cash/api/v1/projects/${projectId}/executions/${cycleId}`,
        paymentVerified: false,
        retirementVerified: false,
      }),
    ),
  });
  const indexPath = join(directory, "public/data/squads-executions.json");
  await mkdir(dirname(indexPath), { recursive: true });
  await writeFile(indexPath, `${JSON.stringify(index, null, 2)}\n`);
}
if (import.meta.main)
  await syncSquadsExecutionRegistry(
    resolve(dirname(fileURLToPath(import.meta.url)), ".."),
  );
